config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :school_registers
  resources :session
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: "user#sign_in"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/school_register.rb
class SchoolRegister < ApplicationRecord
  resourcify
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/school_registers_controller.rb
class SchoolRegistersController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_school_register, only: [:show, :edit, :update, :destroy]

  # GET /school_registers
  # GET /school_registers.json
  def index
    @school_registers = SchoolRegister.all
  end

  # GET /school_registers/1
  # GET /school_registers/1.json
  def show
  end

  # GET /school_registers/new
  def new
    @school_register = SchoolRegister.new
  end

  # GET /school_registers/1/edit
  def edit
  end

  # POST /school_registers
  # POST /school_registers.json
  def create
    @school_register = SchoolRegister.new(school_register_params)

    respond_to do |format|
      if @school_register.save
        format.html { redirect_to @school_register, notice: 'School register was successfully created.' }
        format.json { render :show, status: :created, location: @school_register }
      else
        format.html { render :new }
        format.json { render json: @school_register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_registers/1
  # PATCH/PUT /school_registers/1.json
  def update
    respond_to do |format|
      if @school_register.update(school_register_params)
        format.html { redirect_to @school_register, notice: 'School register was successfully updated.' }
        format.json { render :show, status: :ok, location: @school_register }
      else
        format.html { render :edit }
        format.json { render json: @school_register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_registers/1
  # DELETE /school_registers/1.json
  def destroy
    @school_register.destroy
    respond_to do |format|
      format.html { redirect_to school_registers_url, notice: 'School register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_register
      @school_register = SchoolRegister.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_register_params
      params.require(:school_register).permit(:roll, :name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/school_registers_helper.rb
module SchoolRegistersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Delit</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</body>
</html>

app/views/school_registers/_form.html.erb
<%= form_with(model: school_register, local: true) do |form| %>
  <% if school_register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(school_register.errors.count, "error") %> prohibited this school_register from being saved:</h2>

      <ul>
      <% school_register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :roll %>
    <%= form.number_field :roll, id: :school_register_roll %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :school_register_name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age, id: :school_register_age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/school_registers/edit.html.erb
<h1>Editing School Register</h1>

<%= render 'form', school_register: @school_register %>

<%= link_to 'Show', @school_register %> |
<%= link_to 'Back', school_registers_path %>

app/views/school_registers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>School Registers</h1>

<table>
  <thead>
    <tr>
      <th>Roll</th>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_registers.each do |school_register| %>
      <tr>
        <td><%= school_register.roll %></td>
        <td><%= school_register.name %></td>
        <td><%= school_register.age %></td>
        <td><%= link_to 'Show', school_register %></td>
        <td><%= link_to 'Edit', edit_school_register_path(school_register) %></td>
        <td><%= link_to 'Destroy', school_register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School Register', new_school_register_path %>

app/views/school_registers/new.html.erb
<h1>New School Register</h1>

<%= render 'form', school_register: @school_register %>

<%= link_to 'Back', school_registers_path %>

app/views/school_registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Roll:</strong>
  <%= @school_register.roll %>
</p>

<p>
  <strong>Name:</strong>
  <%= @school_register.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @school_register.age %>
</p>

<%= link_to 'Edit', edit_school_register_path(@school_register) %> |
<%= link_to 'Back', school_registers_path %>